#!/bin/bash
import os,sys,time
#sys1
def jalan(z):
    for e in z + '\n':
        sys.stdout.write(e)
        sys.stdout.flush()
        time.sleep(00000.02)
os.system('clear')

#this logo
logo = ("""\033[1;36m                              __
\033[1;36m          ____  _            |  |        __  __ _   _  ____
\033[1;36m         / ___|(_)_ __    ___|  |___    |  \/  | \ | |/ ___|
\033[1;32m         \___ \| | `__|   \__    __/    | |\/| |  \| |\___ \\
\033[1;32m          ___) | | |         \  /       | |  | | |\  | ___) |
\033[1;31m  __  __ |____/|_|_| _     _  \/ _  __  |_|  |_|_| \_||____/
\033[1;31m |  \/  | __ _ _ __ (_)___| |__ | |/ /   _ _ __ ___   __ _ _ _
\033[1;37m | |\/| |/ _` | `_ \| / __| `_ \| ` / | | | `_ ` _ \ / _` | `_|
\033[1;37m | |  | | (_| | | | | \__ \ | | | . \ |_| | | | | | | (_| | |
\033[1;32m |_|  |_|\__,_|_| |_|_|___/_| |_|_|\_\__,_|_| |_| |_|\__,_|_|""")
#my logo
print(logo)
jalan(" ╭━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━╮ ")
jalan("\033[1;32m |   \033[1;31mCreated By:- https://github.com/SirManishKumar/MNSTools\033[1;32m  | ")
jalan("\033[1;32m |             \033[1;33mMy youtube channel: SirManishKumar\033[1;32m             | ")
jalan("\033[1;32m |             \033[1;33mMy twitter account: SirManishKumar\033[1;32m             | ")
jalan("\033[1;32m |              \033[1;33mMy github account: SirManishKumar\033[1;32m             | ")
jalan("\033[1;32m |            \033[1;33mMy facebook account: SirManishKumar\033[1;32m             | ")
jalan("\033[1;32m ╰━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━╯ ")
print("")
print ("\033[1;31m [1]  \033[1;32m All Pkg        \033[1;31m [10] \033[1;32m Zphisher       \033[1;31m [19] \033[1;32m Metasploit ")
print ("\033[1;31m [2]  \033[1;32m AdvPhishing    \033[1;31m [11] \033[1;32m FotoSploit     \033[1;31m [20] \033[1;32m Lazymux ")
print ("\033[1;31m [3]  \033[1;32m Ngrok          \033[1;31m [12] \033[1;32m EasY_HaCk      \033[1;31m [21] \033[1;32m IP Tracer ")
print ("\033[1;31m [4]  \033[1;32m Termux-ADB     \033[1;31m [13] \033[1;32m T-Phish        \033[1;31m [22] \033[1;32m TermuxLock ") 
print ("\033[1;31m [5]  \033[1;32m PhoneSploit    \033[1;31m [14] \033[1;32m Sayhello       \033[1;31m [23] \033[1;32m MNSTermux ")
print ("\033[1;31m [6]  \033[1;32m Saycheese      \033[1;31m [15] \033[1;32m Lockphish      \033[1;31m [24] \033[1;32m MNSLock ")
print ("\033[1;31m [7]  \033[1;32m Seeker         \033[1;31m [16] \033[1;32m Cam-Hackers    \033[1;31m [25] \033[1;32m MNSNgrok ")
print ("\033[1;31m [8]  \033[1;32m Grabcam        \033[1;31m [17] \033[1;32m Anon-SMS       \033[1;31m [26] \033[1;32m MNSUbuntu ")
print ("\033[1;31m [9]  \033[1;32m Hacklock       \033[1;31m [18] \033[1;32m Tool-X         \033[1;31m [27] \033[1;32m MNSSnake ")
print("")
print ("\033[1;31m [0] \033[1;32m Exit     \033[1;31m  [N] \033[1;32m Next       \033[1;31m [r] \033[1;32m Restart   \033[1;31m [g] \033[1;32m Github ")
print ("\033[1;31m [y] \033[1;32m Youtube   \033[1;31m [f] \033[1;32m Facebook   \033[1;31m [t] \033[1;32m Twitter   \033[1;31m [w] \033[1;32m WhatsApp ")
print("")
nmb = input(" \033[1;32mChoose Number \033[1;31m: ")
print("")
if nmb=="N" "n":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m MNSTools Going To Exit Please Wait.                            ")
    os.system('clear')
    os.system('bash .installer.sh')

if nmb=="0":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m MNSTools Going To Exit Please Wait.                            ")
    os.system('exit')
    os.system('clear')

#Download WhatsApp
elif nmb=="w":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Connecting WhatsApp Please Wait.                          ")
    os.system('xdg-open https://wa.me/+919554988808?text=*From%20MNSTools-*%20I%20Have%20To%20Ask%20For%20 ')
    jalan("\033[1;31m It's finished Thank you for using MNSTools                     ")
    os.system('python install.py ')
#Download Facebook
elif nmb=="f":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Open Facebook Please Wait.                          ")
    os.system('xdg-open https://facebook.com/sirmanishkumar ')
    jalan("\033[1;31m It's finished Thank you for using MNSTools                     ")
    os.system('python install.py ')
#Download Youtube
elif nmb=="y":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Open Youtube Please Wait.                          ")
    os.system('xdg-open https://youtube.com/mnspandit ')
    jalan("\033[1;31m It's finished Thank you for using MNSTools                     ")
    os.system('python install.py ')
#Download Twitter
elif nmb=="t":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Open Twitter Please Wait.                          ")
    os.system('xdg-open https://twitter.com/sirmanishkumar ')
    jalan("\033[1;31m It's finished Thank you for using MNSTools                     ")
    os.system('python install.py ')
#Download Github
elif nmb=="g":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Open Github Please Wait.                          ")
    os.system('xdg-open https://github.com/SirManishKumar ')
    jalan("\033[1;31m It's finished Thank you for using MNSTools                     ")
    os.system('python install.py ')
#Download All Pkg
elif nmb=="1":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download All Pkg Please Wait.                      ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade -y ')
    os.system('pkg update && pkg upgrade -y')
    os.system('pkg install git ')
    os.system('pkg install python ')
    os.system('pip3 install requests ')
    os.system('python3 -m pip install --upgrade pip ')
    os.system('pkg install python2 ')
    os.system('pip2 install requests ')
    os.system('pip install --upgrade pip ')
    os.system('pkg install unzip ')
    os.system('pkg install nano ')
    os.system('apt update && apt upgrade -y ')
    os.system('pkg install figlet ')
    os.system('pkg install curl ')
    os.system('pkg install wget ')
    os.system('pkg install php ')
    os.system('pkg install ruby ')
    os.system('pkg install perl ')
    os.system('pkg install zip ')
    os.system('pkg install unzip ')
    os.system('pkg install openssl-tool ')
    os.system('apt update && apt upgrade -y ')
    os.system('pkg install cmatrix ')
    os.system('pkg install fish ')
    os.system('pkg install openssh ')
    os.system('pip install lolcat ')
    os.system('pip install colorama ')
    os.system('apt –fix-broken install ')
    os.system('clear ')
    os.system('apt update && apt upgrade -y ')
    os.system('clear ')
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('clear ')
    jalan ("\033[1;31m Download All Pkg It's finished Thank you for using MNSTools          ")
    os.system('python install.py ')
#Download AdvPhishing
elif nmb=="2":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download AdvPhishing Please Wait.                  ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('pkg install git ')
    os.system('git clone https://github.com/Ignitetch/AdvPhishing  ')
    os.system('mv AdvPhishing $HOME ')
    os.system('cd && cd AdvPhishing && chmod +x * && bash Android-Setup.sh && bash AdvPhishing.sh')
    jalan("\033[1;31m Download AdvPhishing It's finished Thank you for using MNSTools         ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download Ngrok
elif nmb=="3":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download Ngrok Please Wait.                        ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('pkg install wget ')
    os.system('wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip ')
    os.system('mv ngrok-stable-linux-arm.zip $HOME ')
    os.system('cd && unzip ngrok-stable-linux-arm.zip && chmod 777 ngrok && rm -rf ngrok-stable-linux-arm.zip ')
    jalan("\033[1;31m Download Ngrok It's finished Thank you for using MNSTools         ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download Termux-ADB
elif nmb=="4":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download Termux-ADB Please Wait.                   ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('pkg install wget ')
    os.system('git clone https://github.com/MasterDevX/Termux-ADB ')
    os.system('mv Termux-ADB $HOME ')
    os.system('cd && cd Termux-ADB && chmod +x InstallTools.sh && bash InstallTools.sh ')
    jalan ("\033[1;31m Download Termux-ADB It's finished Thank you for using MNSTools           ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download PhoneSploit
elif nmb=="5":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download PhoneSploit Please Wait.                  ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('pkg install git ')
    os.system('git clone https://github.com/01010000-kumar/PhoneSploit ')
    os.system('mv PhoneSploit $HOME ')
    os.system('cd && cd PhoneSploit && chmod +x phonesploit.py && python phonesploit.py ')
    jalan ("\033[1;31m Download PhoneSploit It's finished Thank you for using MNSTools           ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download Saycheese
elif nmb=="6":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download Saycheese Please Wait.                    ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/Technicalheadquarter/saycheese ')
    os.system('mv saycheese $HOME ')
    os.system('cd && cd saycheese && chmod +x saycheese.sh && ./saycheese.sh ')
    jalan ("\033[1;31m Download Saycheese It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download Seeker
elif nmb=="7":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download Seeker Please Wait.                       ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/thewhiteh4t/seeker ')
    os.system('mv seeker $HOME ')
    os.system('cd && cd seeker && pip install requests && chmod +x seeker.py && python seeker.py -t manual ')
    jalan ("\033[1;31m Download Seeker It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download Grabcam
elif nmb=="8":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download Grabcam Please Wait.                      ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('pip install lolcat ')
    os.system('git clone https://github.com/noob-hackers/grabcam ')
    os.system('mv grabcam $HOME ')
    os.system('cd && cd grabcam && chmod +x grabcam.sh && bash grabcam.sh ')
    jalan ("\033[1;31m Download Grabcam It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download Hacklock
elif nmb=="9":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download Hacklock Please Wait.                     ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('pip install lolcat ')
    os.system('git clone https://github.com/noob-hackers/hacklock ')
    os.system('mv hacklock $HOME ')
    os.system('cd && cd hacklock && chmod +x * && bash setup ')
    jalan ("\033[1;31m Download Hacklock It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download Zphisher
elif nmb=="10":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download Zphisher Please Wait.                     ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone git://github.com/htr-tech/zphisher.git ')
    os.system('mv zphisher $HOME ')
    os.system('cd && cd zphisher && chmod +x saycheese.sh && bash zphisher.sh ')
    jalan ("\033[1;31m Download Zphisher It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download FotoSploit
elif nmb=="11":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download FotoSploit Please Wait.                   ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/Cesar-Hack-Gray/FotoSploit ')
    os.system('mv FotoSploit $HOME ')
    os.system('cd && cd FotoSploit && chmod +x * && bash install.sh && ./FotoSploit ')
    jalan ("\033[1;31m Download FotoSploit It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download EasY_HaCk
elif nmb=="12":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download EasY-HaCk Please Wait.                    ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/sabri-zaki/EasY_HaCk ')
    os.system('mv EasY_HaCk $HOME ')
    os.system('cd && cd EasY_HaCk && chmod +x install.sh && ./install.sh ')
    jalan ("\033[1;31m Download EasY_HaCk It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download T-Phish
elif nmb=="13":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download T-Phish Please Wait.                      ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/Stephin-Franklin/T-Phish ')
    os.system('mv T-Phish $HOME ')
    os.system('cd && cd T-Phish & unzip T-Phish.zip && cd T-Phish && chmod +x * && ./start.sh && ./phish.sh ')
    jalan ("\033[1;31m Download T-Phish It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download Sayhello
elif nmb=="14":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download Sayhello Please Wait.                     ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/deepakverma91123/sayhellodeepak.git ')
    os.system('mv sayhellodeepak $HOME ')
    os.system('cd && cd sayhellodeepak && chmod +x sayhello.sh && bash sayhello.sh ')
    jalan ("\033[1;31m Download Sayhello It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download Lockphish
elif nmb=="15":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download Lockphish Please Wait.                    ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/kali-linux-tutorial/lockphish ')
    os.system('mv lockphish $HOME ')
    os.system('cd && cd lockphish && chmod +x lockphish.sh && bash lockphish.sh ')
    jalan ("\033[1;31m Download Lockphish It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download Cam-Hackers
elif nmb=="16":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download Cam-Hackers Please Wait.                  ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/AngelSecurityTeam/Cam-Hackers ')
    os.system('mv Cam-Hackers $HOME ')
    os.system('cd && cd Cam-Hackers && chmod +x cam-hackers.py && python3 cam-hackers.py ')
    jalan ("\033[1;31m Download Cam-Hackers It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download Anon-SMS
elif nmb=="17":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download Anon-SMS Please Wait.                     ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/HACK3RY2J/Anon-SMS.git ')
    os.system('mv Anon-SMS $HOME ')
    os.system('cd && cd Anon-SMS && chmod +x * && bash Run.sh ')
    jalan ("\033[1;31m Download Anon-SMS It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download Tool-X
elif nmb=="18":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download Tool-X Please Wait.                       ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/Rajkumrdusad/Tool-X.git ')
    os.system('mv Tool-X $HOME ')
    os.system('cd && cd Tool-X && chmod +x install.aex && ./install.aex ')
    jalan ("\033[1;31m Download Tool-X It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download Metasploit
elif nmb=="19":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download Metasploit Please Wait.                   ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone http://github.com/rooted-cyber/Metasploit-Installation ')
    os.system('mv Metasploit-Installation $HOME ')
    os.system('cd && cd Metasploit-Installation && chmod +x setup.sh && bash setup.sh && bash metasploit.sh ')
    jalan ("\033[1;31m Download Metasploit It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download Lazymux
elif nmb=="20":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download Lazymux Please Wait.                      ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/Gameye98/Lazymux ')
    os.system('mv Lazymux $HOME ')
    os.system('cd && cd Lazymux && chmod +x lazymux.py && python lazymux.py ')
    jalan ("\033[1;31m Download Lazymux It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download MNSLock
elif nmb=="24":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download MNSLock Please Wait.                      ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/SirManishKumar/MNSLock ')
    os.system('mv MNSLock $HOME ')
    os.system('cd && cd MNSLock && chmod +x install.sh && bash install.sh ')
    os.system('cd && rm -rf MNSLock ')
    jalan ("\033[1;31m Download MNSLock It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download TermuxLock
elif nmb=="22":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download TermuxLock Please Wait.                   ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/SirManishKumar/TermuxLock ')
    os.system('mv TermuxLock $HOME ')
    os.system('cd && cd TermuxLock && chmod +x install.sh && bash install.sh ')
    os.system('cd && rm -rf TermuxLock ')
    jalan ("\033[1;31m Download TermuxLock It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download MNSTermux
elif nmb=="23":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download MNSTermux Please Wait.                    ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/SirManishKumar/MNSTermux ')
    os.system('mv MNSTermux $HOME ')
    os.system('cd && cd MNSTermux && chmod +x setup.sh && bash setup.sh ')
    os.system('cd && rm -rf MNSTermux ')
    jalan ("\033[1;31m Download MNSTermux It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download IP Tracer
elif nmb=="21":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download IP Tracer Please Wait.                    ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/rajkumardusad/IP-Tracer.git ')
    os.system('mv IP-Tracer $HOME ')
    os.system('cd && cd IP-Tracer && chmod +x install && ./install ')
    jalan ("\033[1;31m Download IP Tracer It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download MNSNgrok
elif nmb=="25":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download MNSNgrok Please Wait.                     ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/SirManishKumar/MNSNgrok ')
    os.system('mv MNSNgrok $HOME ')
    os.system('cd && cd MNSNgrok && chmod +x setup.sh && bash setup.sh ')
    os.system('cd && rm -rf MNSNgrok ')
    jalan ("\033[1;31m Download MNSNgrok It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download MNSUbuntu
elif nmb=="26":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download MNSUbuntu Please Wait.                    ")
    os.system('termux-setup-storage ')
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/SirManishKumar/MNSUbuntu ')
    os.system('mv MNSUbuntu $HOME ')
    os.system('cd && cd MNSUbuntu && chmod +x ubuntu.sh && ./ubuntu.sh && ./startubuntu.sh ')
    os.system('exit ')
    jalan ("\033[1;31m....................Start Ubuntu Type \033[1;34m./startubuntu.sh\033[1;31m.......................")
    jalan ("\033[1;31m Download MNSUbuntu It's Finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download MNSSnake
elif nmb=="27":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download Please Wait.                    ")
    os.system('apt update && apt upgrade')
    os.system('git clone https://github.com/SirManishKumar/MNSSnake ')
    os.system('mv MNSSnake $HOME ')
    os.system('cd && cd MNSSnake && chmod +x snake.py && rm -rf nn_1.py nn_2.py && python snake.py ')
    jalan ("\033[1;31m Download MNSSnake It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Download Update MNSTools
elif nmb=="99":
    jalan("\033[1;31m Contacting To Server Please Wait.............................💯")
    jalan("\033[1;33m Starting To Download MNSTools Please Wait.                     ")
    os.system('apt update && apt upgrade')
    os.system('pkg install python -y ')
    os.system('clear ')
    jalan ("\033[1;31m Updated MNSTools It's finished Thank you for using MNSTools               ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
#Try ouvert my tool
else :
    print ("\033[1;31m                  X_False number try again_X         ")
    os.system('figlet MNSTools ')
    time.sleep(000.10)
    os.system('python install.py ')
