#!/bin/bash
#version 1.0
clear
green="\e[1;32m"
yellow="\033[33;1m"
indigo="\033[34;1m"
red="\033[35;1m"
purple="\033[37;1m"
cyan="\033[36;1m"
white="\033[39;1m"

printf "\e[1;32m\t+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+\e[0m\n"
printf "\e[1;37m\t      |A|l|l|T|o|o|l|s|   \e[0m\n"
printf "\e[1;32m\t+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+\e[0m\n"
printf "\n"
printf "\e[1;40m\tCreated by:\e[0m\e[1;42mSirManishKumar\e[0m\n"
printf "\n"

printf "\e[1;93m==============[\e[0m\e[1;95mAll Tools Installer]\e[0m\e[1;93m===============\e[0m\n"
sleep 1
###################################################
# CTRL + C
###################################################
trap ctrl_c INT
ctrl_c() {
clear
echo "Author : Manish Kumar Chaturvedi" | lolcat
figlet -f slant "AllTools" | lolcat
sleep 1
exit
}

lagi=1
while [ $lagi -lt 6 ];
do
echo -e "\e[1;36m"
echo ' 1. Updates AllTools'
echo ' 2. Install MNSTermux'
echo ' 3. Install MNSUbuntu'
echo ' 4. Install MNSNgrok'
echo ' 5. Install MNSLock'
echo ' 6. Install MNSSnake'
echo ' 7. Install MNSTools'
echo ' 8. Install TermuxLock'
echo ' 9. Install TermuxTool'
echo '10. Install TermuxHack'
echo "========================================================" | lolcat
echo "            00. Exit            N. Next" | lolcat
echo "========================================================" | lolcat
echo -e "\e[1;32m╭─[ Select number to install ]"
read -p "╰─> " pil;
case $pil in
1) echo " Contacting To Server Please Wait.............................💯" | lolcat
   echo " Starting To Download All Pkg Please Wait.                      " | lolcat
   termux-setup-storage
   apt update && apt upgrade -y
   pkg update && pkg upgrade -y
   pkg install git
   pkg install python
   pip3 install requests
   python3 -m pip install --upgrade pip
   pkg install python2
   pip2 install requests
   pip install --upgrade pip
   pkg install unzip
   pkg install nano
   apt update && apt upgrade -y
   pkg install figlet
   pkg install curl
   pkg install wget
   pkg install php
   pkg install ruby
   pkg install perl
   pkg install zip
   pkg install unzip
   pkg install openssl-tool
   apt update && apt upgrade -y
   pkg install cmatrix
   pkg install fish
   pkg install openssh
   pip install lolcat
   pip install colorama
   apt –fix-broken install
   clear
   apt update && apt upgrade -y
   clear
   figlet Update
   figlet AllTools
   
;;
2) git clone https://github.com/SirManishKumar/MNSTermux

;;
3) git clone https://github.com/SirManishKumar/MNSUbuntu

;;
4) git clone https://github.com/SirManishKumar/MNSNgrok
   mv MNSNgrok $HOME
   cd
   cd MNSNgrok
   chmod +x setup.sh
   bash setup.sh
   cd && rm -rf MNSNgrok

;;
5) git clone https://github.com/SirManishKumar/MNSLock
   mv MNSLock $HOME
   cd
   cd MNSLock
   chmod +x install.sh
   bash install.sh
   cd && rm -rf MNSLock

;;
6) git clone https://github.com/SirManishKumar/MNSSnake

;;
7) git clone https://github.com/SirManishKumar/MNSTools
   mv MNSTools $HOME
   cd
   cd MNSTools
   chmod +x *
   python install.py

;;
8) git clone https://github.com/SirManishKumar/TermuxLock

;;
9) git clone https://github.com/SirManishKumar/TermuxTool

;;
00) echo "Author : Manish Kumar Chaturvedi" | lolcat
echo "Github: https://github.com/SirManishKumar/AllTools" | lolcat
figlet -f slant "AllTools" | lolcat
sleep 1
exit
;;
N) clear
bash .1.sh
;;
n) clear
bash .1.sh
;;
esac
done
done
