#!/bin/bash
#version 1.0
clear
green="\e[1;32m"
yellow="\033[33;1m"
indigo="\033[34;1m"
red="\033[35;1m"
purple="\033[37;1m"
cyan="\033[36;1m"
white="\033[39;1m"

printf "\e[1;32m\t    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+\e[0m\n"
printf "\e[1;37m\t               |M|N|S|A|l|l|T|o|o|l|s|   \e[0m\n"
printf "\e[1;32m\t    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+\e[0m\n"
printf "\n"
printf "\e[1;40m\t            Created by:\e[0m\e[1;42mSirManishKumar\e[0m\n"
printf "\n"

printf "\e[1;93m====================[\e[0m\e[1;95mAll Tools Installer]\e[0m\e[1;93m=====================\e[0m\n"
sleep 1
###################################################
# CTRL + C
###################################################
trap ctrl_c INT
ctrl_c() {
clear
echo "Author : Manish Kumar Chaturvedi" | lolcat
figlet -f slant "MNSAllTools" | lolcat
sleep 1
exit
}

lagi=1
while [ $lagi -lt 6 ];
do
figlet -f slant "MNSAllTools" | lolcat
echo " ╭━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━╮" | lolcat
echo "   Created By:- https://github.com/SirManishKumar/MNSAllTools " | lolcat
echo "      Follow On Twitter:- http://twtter.com/SirManishKumar " | lolcat
echo " ╰━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━━ ━━━━━╯" | lolcat
echo -e "\e[1;36m"
echo ' 1. Updates Basic Tools        ╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮'
echo ' 2. Install MNSTermux          |    u. Update & Upgrade     |'
echo ' 3. Install MNSUbuntu          |         r. Restart         |'
echo ' 4. Install MNSNgrok           |         g. Github          |'
echo ' 5. Install MNSLock            |         y. Youtube         |'
echo ' 6. Install MNSSnake           |         f. Facebook        |'
echo ' 7. Install MNSTools           |         t. Twitter         |'
echo ' 8. Install TermuxLock         |         w. WhatsApp        |'
echo ' 9. Install TermuxTool         |  github.com/SirManishKumar |'
echo '10. Install TermuxHack         ╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯'
echo "=============================================================" | lolcat
echo "      Dear Friends Please Enter 'N' To Install 350 Tools " | lolcat
echo "                  0. Exit            N. Next" | lolcat
echo "=============================================================" | lolcat
echo -e "\e[1;32m╭─[ Select number to install ]"
read -p "╰──> " pil;
case $pil in
u) echo " Contacting To Server Please Wait.............................💯" | lolcat
   echo " Starting To Download MNSUpgrade Please Wait.                   " | lolcat
   apt update && apt upgrade
   pkg install python -y
   git clone https://github.com/SirManishKumar/MNSUpgrade
   mv MNSUpgrade $HOME
   cd && cd MNSUpgrade
   bash Upgrade.sh
   echo " It's finished Thank you for using MNSAllTools                  " | lolcat
   figlet MNSAllTools
   clear

;;
w) echo " Contacting To Server Please Wait.............................💯" | lolcat
   echo " Starting To Connecting WhatsApp Please Wait.                   " | lolcat
   xdg-open https://wa.me/+919554988808?text=*From%20MNSAllTools-*%20I%20Have%20To%20Ask%20For%20
   echo " It's finished Thank you for using MNSAllTools                  " | lolcat
   clear

;;
f) echo " Contacting To Server Please Wait.............................💯" | lolcat
   echo " Starting To Open Facebook Please Wait.                         " | lolcat
   xdg-open https://facebook.com/sirmanishkumar
   echo " It's finished Thank you for using MNSAllTools                  " | lolcat
   clear

;;
y) echo " Contacting To Server Please Wait.............................💯" | lolcat
   echo " Starting To Open Youtube Please Wait.                          " | lolcat
   xdg-open https://youtube.com/mnspandit
   echo " It's finished Thank you for using MNSAllTools                  " | lolcat
   clear

;;
t) echo " Contacting To Server Please Wait.............................💯" | lolcat
   echo " Starting To Open Twitter Please Wait.                          " | lolcat
   xdg-open https://twitter.com/sirmanishkumar
   echo " It's finished Thank you for using MNSAllTools                  " | lolcat
   clear

;;
g) echo " Contacting To Server Please Wait.............................💯" | lolcat
   echo " Starting To Open Github Please Wait.                           " | lolcat
   xdg-open https://github.com/SirManishKumar
   echo " It's finished Thank you for using MNSAllTools                  " | lolcat
   clear

;;
1) echo " Contacting To Server Please Wait.............................💯" | lolcat
   echo " Starting To Update Basic Tools Please Wait.                    " | lolcat
   termux-setup-storage
   apt update && apt upgrade -y
   pkg update && pkg upgrade -y
   pkg install git
   pkg install python
   pip3 install requests
   python3 -m pip install --upgrade pip
   pkg install python2
   pip2 install requests
   pip install --upgrade pip
   pkg install unzip
   pkg install nano
   apt update && apt upgrade -y
   pkg install figlet
   pkg install curl
   pkg install wget
   pkg install php
   pkg install ruby
   pkg install perl
   pkg install zip
   pkg install unzip
   pkg install openssl-tool
   apt update && apt upgrade -y
   pkg install cmatrix
   pkg install fish
   pkg install openssh
   pip install lolcat
   pip install colorama
   apt –fix-broken install
   clear
   apt update && apt upgrade -y
   clear
   echo " It's finished Thank you for using MNSAllTools                  " | lolcat
   figlet MNSAllTools
   clear

;;
2) echo " Contacting To Server Please Wait.............................💯" | lolcat
   echo " Starting To Download MNSTermux Please Wait.                    " | lolcat
   git clone https://github.com/SirManishKumar/MNSTermux
   mv MNSTermux $HOME
   cd
   cd MNSTermux
   chmod +x setup.sh
   bash setup.sh
   echo " It's finished Thank you for using MNSAllTools                  " | lolcat
   figlet MNSAllTools
   clear

;;
3) echo " Contacting To Server Please Wait.............................💯" | lolcat
   echo " Starting To Download MNSUbuntu Please Wait.                    " | lolcat
   git clone https://github.com/SirManishKumar/MNSUbuntu
   mv MNSUbuntu $HOME
   cd
   cd MNSUbuntu
   chmod +x ubuntu.sh
   ./ubuntu.sh -y
   ./startubuntu.sh
   exit
   echo " It's finished Thank you for using MNSAllTools                  " | lolcat
   figlet MNSAllTools
   clear

;;
4) echo " Contacting To Server Please Wait.............................💯" | lolcat
   echo " Starting To Download MNSNgrok Please Wait.                     " | lolcat
   git clone https://github.com/SirManishKumar/MNSNgrok
   mv MNSNgrok $HOME
   cd
   cd MNSNgrok
   chmod +x setup.sh
   bash setup.sh
   cd && rm -rf MNSNgrok
   echo " It's finished Thank you for using MNSAllTools                  " | lolcat
   figlet MNSAllTools
   clear

;;
5) echo " Contacting To Server Please Wait.............................💯" | lolcat
   echo " Starting To Download MNSLock Please Wait.                      " | lolcat
   git clone https://github.com/SirManishKumar/MNSLock
   mv MNSLock $HOME
   cd
   cd MNSLock
   chmod +x install.sh
   bash install.sh
   cd && rm -rf MNSLock
   echo " It's finished Thank you for using MNSAllTools                  " | lolcat
   figlet MNSAllTools
   clear

;;
6) echo " Contacting To Server Please Wait.............................💯" | lolcat
   echo " Starting To Download MNSSnake Please Wait.                     " | lolcat
   git clone https://github.com/SirManishKumar/MNSSnake
   mv MNSSnake $HOME
   cd
   cd MNSSnake
   chmod +x snake.py
   python snake.py
   echo " It's finished Thank you for using MNSAllTools                  " | lolcat
   figlet MNSAllTools
   clear

;;
7) echo " Contacting To Server Please Wait.............................💯" | lolcat
   echo " Starting To Download MNSTools Please Wait.                     " | lolcat
   git clone https://github.com/SirManishKumar/MNSTools
   mv MNSTools $HOME
   cd
   cd MNSTools
   chmod +x *
   python install.py
   echo " It's finished Thank you for using MNSAllTools                  " | lolcat
   figlet MNSAllTools
   clear

;;
8) echo " Contacting To Server Please Wait.............................💯" | lolcat
   echo " Starting To Download TermuxLock Please Wait.                   " | lolcat
   git clone https://github.com/SirManishKumar/TermuxLock
   mv TermuxLock $HOME
   cd
   cd TermuxLock
   chmod +x install.sh
   bash install.sh
   echo " It's finished Thank you for using MNSAllTools                  " | lolcat
   figlet MNSAllTools
   clear

;;
9) echo " Contacting To Server Please Wait.............................💯" | lolcat
   echo " Starting To Download TermuxTool Please Wait.                   " | lolcat
   git clone https://github.com/SirManishKumar/TermuxTool
   mv TermuxTool $HOME
   cd
   cd TermuxTool
   chmod +x setup.sh
   bash setup.sh
   echo " It's finished Thank you for using MNSAllTools                  " | lolcat
   figlet MNSAllTools
   clear

;;
0) echo "Author : Manish Kumar Chaturvedi" | lolcat
echo "Website : https://mnsgranth.com" | lolcat
echo "Github: https://github.com/SirManishKumar/MNSAllTools" | lolcat
figlet -f slant "MNSAllTools" | lolcat
sleep 1
clear
exit
;;
N) clear
bash .1.sh
;;
n) clear
bash .1.sh
;;
esac
done
done
